Repository SPACEMAP-WEB/spacemap-platform, pull requests merged in 2022-07, with the labels that each got.

#46 fix: fix accessor error
  src/app.feature/watcherCatcher/components/WCDBDetailTable.tsx
  src/app.feature/watcherCatcher/components/WCDBTable.tsx
Labels: 버그수정

#52 feat/cesium
  Procfile
  buildspec.yml
  src/app.components/Cesium.jsx
  src/app.modules/cesium/cesiumContainer.js
  src/app.modules/cesium/cesiumModule.js
  src/app.modules/cesium/cesiumOption.js
  src/app.store/cesium/cesiumModules.ts
  src/app.store/cesium/cesiumReducer.ts
  src/app.store/cesium/store.cesium.ts
  src/app.store/cesium/type.ts
  src/app.store/config/configureStore.ts
  src/pages/index.tsx
Labels: Develop

#53 fix: refactoring codes
  src/app.components/button/Button.tsx
  src/app.components/button/LoginButton.tsx
  src/app.feature/conjunctions/hooks/useConjunctionsEventHandler.ts
  src/app.feature/conjunctions/screen/Conjunctions.tsx
  src/app.feature/favorites/component/FavoritesSubscription.tsx
  src/app.feature/favorites/screen/Favorites.tsx
  src/app.feature/launchConjunctions/components/LPDBTable.tsx
  src/app.feature/launchConjunctions/screen/LaunchConjunctions.tsx
  src/app.feature/sideMenu/screen/SideMenu.tsx
  src/app.feature/watcherCatcher/components/WCDBTable.tsx
Labels: 리팩토링

#55 Feat/cesiumConjuctions
  src/app.feature/conjunctions/component/ConjunctionsTable.tsx
  src/app.feature/conjunctions/component/TableColumns.tsx
  src/app.feature/favorites/component/FavoritesTable.tsx
  src/app.feature/favorites/component/TableColumns.tsx
  src/app.feature/launchConjunctions/components/LPDBDetailTable.tsx
  src/app.feature/watcherCatcher/components/WCDBDetailTable.tsx
  src/app.modules/cesium/cesiumContainer.js
  src/app.modules/cesium/cesiumModule.js
  src/app.modules/cesium/cesiumOption.js
  src/app.modules/cesium/drawCzml.ts
  src/app.store/cesium/cesiumModules.ts
  src/app.store/cesium/cesiumReducer.ts
  src/app.store/cesium/store.cesium.ts
  src/app.store/cesium/type.ts
  src/app.store/cesium/useCesiumState.ts
Labels: 신규기능, 리팩토링, Develop

#57 lca
  src/app.components/MainLayout.tsx
  src/app.feature/conjunctions/component/ConjunctionsTable.tsx
  src/app.feature/conjunctions/screen/Conjunctions.tsx
  src/app.feature/favorites/screen/Favorites.tsx
  src/app.feature/launchConjunctions/components/LPDBDetailTable.tsx
  src/app.feature/launchConjunctions/components/LPDBTable.tsx
  src/app.feature/launchConjunctions/screen/LaunchConjunctions.tsx
  src/app.feature/watcherCatcher/components/WCDBDetailTable.tsx
  src/app.feature/watcherCatcher/components/WCDBTable.tsx
  src/app.feature/watcherCatcher/screen/WatcherCatcher.tsx
  src/app.store/cesium/cesiumModules.ts
  src/app.store/cesium/cesiumReducer.ts
  src/app.store/cesium/store.cesium.ts
  src/app.store/cesium/type.ts
  src/pages/index.tsx
  src/pages/main/index.tsx
Labels: 신규기능, 리팩토링, Develop

#58 Feat/table sort box
  .prettierrc
  src/app.components/ConfigBox.tsx
  src/app.components/ConfigBoxItem.tsx
  src/app.feature/conjunctions/component/ConjunctionsTable.tsx
  src/app.feature/conjunctions/component/TableColumns.tsx
  src/app.feature/conjunctions/hooks/useConjunctionsEventHandler.ts
  src/app.feature/conjunctions/module/ppdbDataRefactor.ts
  src/app.feature/conjunctions/screen/Conjunctions.tsx
  src/app.feature/conjunctions/style/tableStyle.ts
  src/app.feature/conjunctions/types/conjunctions.ts
  src/app.feature/favorites/component/FavoritesSubscriptionTable.tsx
  src/app.feature/favorites/component/FavoritesTable.tsx
  src/app.modules/hooks/useTimeFormatHandler.ts
  src/app.modules/types/time.ts
  src/app.modules/util/remainingTimeChecker.ts
  src/app.store/config/configureStore.ts
  src/app.store/timeFormatStore/store.timeFormatApp.ts
  src/pages/main/index.tsx
  tsconfig.json
Labels: 신규기능, 퍼블리싱

#65 Feat/remaining time rendering
  src/app.feature/conjunctions/component/ConjunctionsTable.tsx
  src/app.feature/conjunctions/module/ppdbDataRefactor.ts
  src/app.modules/util/remainingTimeChecker.ts
  src/app.modules/util/timeCounter.ts
Labels: 신규기능, Develop

#69 Feat/cesium module type
  src/app.modules/cesium/drawCzml.ts
Labels: 리팩토링, Develop

#89 Develop
  src/app.components/modal/SuccessModal.tsx
  src/app.feature/launchConjunctions/components/AssessmentModal.tsx
  src/app.feature/launchConjunctions/components/SuccessModal.tsx
  src/app.feature/launchConjunctions/query/useMutationLPDB.ts
  src/app.feature/launchConjunctions/query/useQueryLPDB.ts
  src/app.feature/launchConjunctions/types/launchConjunctions.ts
  src/app.feature/watcherCatcher/components/SearchModal.tsx
  src/app.feature/watcherCatcher/components/SuccessModal.tsx
  src/app.feature/watcherCatcher/types/watcherCatcher.ts
Labels: Production
